name: Build and publish

on:
  push:
    tags:
      - "ozobot-*-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
         
    - name: Build packages
      env:
        SETUPTOOLS_SCM_PRETEND_METADATA: '{node=""}'
      run: |
        # we need to build sdist and wheel separately, otherwise the wheel is empty
        uv build --all-packages --sdist
        uv build --all-packages --wheel

    - name: Upload github artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  check-tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      has-release-tag: ${{ steps.check.outputs.has-release-tag }}
      has-tag: ${{ steps.check.outputs.has-tag }}
      package-name: ${{ steps.check.outputs.package-name }}
    steps:
    - id: check
      run: |
        ref="${{ github.ref_name }}"
        if   [[ "$ref" =~ ^([a-zA-Z0-9_-]+)-v([0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+)$ ]]; then
          echo "has-release-tag=false" >> $GITHUB_OUTPUT
          echo "has-tag=true" >> $GITHUB_OUTPUT
          package_name="${BASH_REMATCH[1]}"
        elif [[ "$ref" =~ ^([a-zA-Z0-9_-]+)-v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
          echo "has-release-tag=true" >> $GITHUB_OUTPUT
          echo "has-tag=true" >> $GITHUB_OUTPUT
          package_name="${BASH_REMATCH[1]}"
        else
          echo "has-tag=false" >> $GITHUB_OUTPUT
          echo "has-release-tag=false" >> $GITHUB_OUTPUT
          echo "Unsupported tag format" 1&>2
          exit 1
        fi

        echo "package-name=$package_name" >> $GITHUB_OUTPUT

  publish-to-testpypi:
    needs: [build, check-tag]
    if: needs.check-tag.outputs.has-tag == 'true'
    
    name: "${{ needs.check-tag.outputs.package-name }}: publish to TestPyPI"
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/${{ needs.check-tag.outputs.package-name }}
      
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact ${{ needs.check-tag.outputs.package-name }}
      uses: ./.github/actions/download-python-dist
      with:
        package-name: ${{ needs.check-tag.outputs.package-name }}
    - name: Publish distribution package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
  publish-to-pypi:
    needs: [build, check-tag]
    if: needs.check-tag.outputs.has-release-tag == 'true'
    
    name: "${{ needs.check-tag.outputs.package-name }}: publish to PyPI"
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ needs.check-tag.outputs.package-name }}

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact ${{ needs.check-tag.outputs.package-name }}
      uses: ./.github/actions/download-python-dist
      with:
        package-name: ${{ needs.check-tag.outputs.package-name }}
    - name: Publish distribution package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
