name: Test

on:
  push:
  pull_request:
    types: [opened]

jobs:
  generate-jobs:
    # taken from https://nox.thea.codes/en/stable/cookbook.html
    runs-on: ubuntu-latest
    outputs:
      sessions: ${{ steps.set-matrix.outputs.sessions }}
    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v6
    
    - id: set-matrix
      shell: bash
      run: |
        echo sessions=$(uv run nox --json -l | jq -c '[.[] | {"name", "session"}]') | tee --append $GITHUB_OUTPUT

  check-lockfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Check lockfile consistency
      shell: bash
      run: |
        uv lock --check

  test:
    name: check - ${{ matrix.session.session }}
    needs: [generate-jobs]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.generate-jobs.outputs.sessions) }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    # We cannot pass arguments via the `services` section,
    # so we'll need to start websockify the container manually.
    # https://github.com/orgs/community/discussions/160506
    # We cannot pass arguments via the `services` section,
    # so we'll need to start websockify the container manually.
    - name: Create rabbitmq docker network
      run: |
        docker network create rmq-network
    - name: Run rabbitmq
      if: ${{ matrix.session.name == 'test' }}
      run: |
        docker run --detach \
          --network rmq-network \
          --name rabbitmq \
          --publish 5672:5672 \
          rabbitmq:4
        
    - name: Run websockify
      if: ${{ matrix.session.name == 'test' }}
      run: |
        docker run --detach \
          --network rmq-network \
          --health-cmd "rabbitmq-diagnostics -q ping" \
          --health-interval 30s \
          --health-timeout 30s \
          --health-retries 5 \
          --name websockify \
          --publish 15670:15670 \
          jwnmulder/websockify 15670 "rabbitmq:5672" 
          
    - name: Run tests
      run: |
        uv run \
          --frozen \
          nox \
          -s ${{ matrix.session.session }}
